[package]
name = "nes_emulator"
version = "0.1.0"
authors = ["Jack Kilrain", "Jayden Elliott"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
